(function(_ds){var window=this;var ZQ=function(a,b){_ds.Wn(a,"transform","translate3d("+b+"px,0px,0px)")};var bR=function(a){a.j=$Q(a,".devsite-top-logo-row-wrapper-wrapper");a.g=$Q(a,".devsite-collapsible-section");a.m=$Q(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.j}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.m}`);a.style.setProperty("--devsite-js-top-row--height",`${a.j}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.g}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.m}px`);aR(a);a.h.resolve()},aR=
function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.m&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.ya&&(_ds.Wn(b,"transform",`translate3d(0, -${a.offset}px, 0)`),cR(a),a.ya=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.ma()}px`)},Bva=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");
const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){a.ra.removeAll();a.oa&&window.cancelAnimationFrame(a.oa);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.Vj(b.offsetWidth,b.offsetHeight);b=new _ds.Vj(c.offsetWidth,c.offsetHeight);var f=_ds.to(c,"margin"),g=document.documentElement.getAttribute("dir")==="rtl"?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?
e:0,l=f?h:1;_ds.Wn(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});ZQ(c,a.hasAttribute("search-active")?0:e);a.ra.Gb(d,_ds.el,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),ZQ(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.oa=window.requestAnimationFrame(()=>{c.setAttribute("transition","");_ds.Wn(d,"transform",
"scale3d("+l+",1,1)");ZQ(c,k)})}},Cva=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=a==null?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Zl(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===
d&&e.focus(),c.setAttribute("disabled","")))}},Dva=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.getBrowserEvent();_ds.al(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{document.body.removeAttribute("devsite-book-nav--open")});a.eventHandler.listen(window,"resize",()=>{dR(a)});a.eventHandler.listen(document.body,["devsite-page-loaded",
"devsite-content-updated"],()=>{dR(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||b.target.getAttribute("id")!=="devsite-hamburger-menu"||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},eR=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");
b.style.opacity="1";a.appendChild(b)}},cR=function(a){a.g===0?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},dR=function(a){window.requestAnimationFrame(()=>{a.va.hb()})},$Q=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},fR=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=
0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},gR=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Gj(a,c,b))},Eva=class extends _ds.Hj{constructor(){super(...arguments);this.eventHandler=new _ds.E;this.ya=-1;this.ra=new _ds.E;this.oa=0;this.qa=new MutationObserver(()=>{bR(this)});this.va=new _ds.Mn(()=>{bR(this);cR(this)},15);this.authUser=void 0;this.offset=this.m=this.g=this.j=0;this.updated=!1;this.h=new _ds.ug}static get observedAttributes(){return["offset",
"search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;aR(this);break;case "search-active":Bva(this);break;case "bottom-row--hidden":a=c!==null,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),Cva(this,a)}}connectedCallback(){Dva(this);eR(this);cR(this);
bR(this);this.qa.observe(this,{childList:!0,subtree:!0});aR(this);const a=_ds.C();this.authUser=_ds.Al(_ds.Bl(a.href),"authuser")}disconnectedCallback(){this.eventHandler.removeAll();this.qa.disconnect()}ma(){return this.j+this.g-this.offset}ua(){return this.j+this.g}ad(a){this.h&&this.h.resolve();this.h=new _ds.ug;this.updated=!1;if(a){gR(this,a,".devsite-header-upper-tabs");gR(this,a,".devsite-collapsible-section");gR(this,a,".devsite-product-name-wrapper");gR(this,a,"devsite-language-selector");
gR(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&fR(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(fR(c,b),c=_ds.C(),c=_ds.Al(_ds.Bl(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Gj(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.Gj(this,this.querySelector(".devsite-header-link"),
a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Ek(this),this.appendChild(a));eR(this);dR(this)}async ready(){return this.h.promise}};try{customElements.define("devsite-header",Eva)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
