(function(_ds){var window=this;var fsa=function(){return(0,_ds.V)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},gsa=function(){return(0,_ds.V)('<div class="devsite-book-nav-blur"></div>')},hsa=function(a){a=a.XI;a=_ds.GC(new _ds.EC("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.Y(_ds.Ys(1)),XXX_2:_ds.Y(_ds.Ys(a))});return(0,_ds.V)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var isa="onpointerover"in window?"pointerover":"mouseover",LN=function(a){const b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Ej(a,"visually-hidden","",c))},jsa=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:
0;a.eventHandler.Gb(a,_ds.el,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.m.removeAttribute("animatable")});_ds.Ej(a,"animatable","");b=_ds.rf(a.ea`animatable`);b(a.background,"animatable","");b(a.m,"animatable","");a.hasAttribute("collapsed")?(_ds.Ej(a,"aria-label","Hide side navigation",a.g),_ds.Ej(a,"data-title","Hide side navigation",a.g),a.removeAttribute("collapsed"),_ds.AH(a.g,"expanded","true"),MN(a,"Expanded book nav")):(_ds.Ej(a,"aria-label","Show side navigation",
a.g),_ds.Ej(a,"data-title","Show side navigation",a.g),_ds.Ej(a,"collapsed",""),_ds.AH(a.g,"expanded","false"),MN(a,"Collapsed book nav"),a.eventHandler.Gb(a,_ds.el,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.Zl();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},lsa=function(a){a.eventHandler.listen(a,"click",b=>void NN(a,b));a.eventHandler.listen(a,"keypress",b=>{b.keyCode===13&&NN(a,b)});a.eventHandler.listen(a,
[isa,"focusin"],b=>void ksa(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.j&&(ON(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Ej(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.ua.hb());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.ua.hb()});a.eventHandler.listen(a,"scroll",()=>{_ds.Ej(a,"user-scrolled","")});a.eventHandler.listen(a.g,"click",()=>{a.xa.hb()});a.h&&(a.eventHandler.listen(a.h,"keyup",()=>void a.va.hb()),
a.eventHandler.listen(a.h,"focus",()=>void PN(a,"focus")));a.oa&&a.eventHandler.listen(a.oa,["click","keydown"],b=>{if(b.type==="click"||b.keyCode===13||b.keyCode===27){a.h&&(a.h.value="",a.h.focus());let c;(c=a.oa)==null||c.classList.add("hidden");QN(a);RN(a);PN(a,b.type)}})},SN=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.ma=new Set(b);if(!_ds.C().hash&&c)msa(a,a.ma);else{c=new _ds.xH;for(const d of a.ma)_ds.wH(c,d)}},TN=async function(a){const b=await _ds.v();for(const c of a.ma)b.unregisterIntersectionForElement(c)},
NN=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Ej(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&ON(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.Ej(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.j&&(d=a.j.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},ksa=function(a,b){b.defaultPrevented||(b=_ds.$k(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.lf(b,_ds.Sl(b.href).href))},PN=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",
action:b,label:b==="focus"?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},UN=function(a){a.ra=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},WN=function(a){const b=_ds.C().searchParams.get("nf");a.h&&b&&(a.h.value=b,VN(a))},VN=function(a){if(a.ra.length){QN(a);RN(a);var b,c,d=(b=a.h)==null?void 0:(c=b.value)==null?void 0:c.trim().toLowerCase();if(d){var e;(e=a.oa)==
null||e.classList.remove("hidden");for(const g of a.ra){var f=g.querySelectorAll(".devsite-nav-text");a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l;const m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:[]).some(q=>q.toLowerCase().includes(d));let n,p;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(p=n.textContent)==null?0:p.toLowerCase().includes(d))))e=c=!0;else for(const q of f){let r,u,y,B;f=((B=(r=q)==null?
void 0:(u=r.parentElement)==null?void 0:(y=u.getAttribute("data-synonyms"))==null?void 0:y.split(","))!=null?B:[]).some(D=>D.toLowerCase().includes(d));if(d){let D;if(f||((D=q.textContent)==null?0:D.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const q of c){q.classList.remove("hidden");let r,u,y,B;c=((B=(r=q)==null?void 0:(u=r.parentElement)==null?void 0:(y=u.getAttribute("data-synonyms"))==null?void 0:
y.split(","))!=null?B:[]).some(J=>J.toLowerCase().includes(d));let D;d&&(c||((D=q.textContent)==null?0:D.toLowerCase().includes(d)))&&++b}}nsa(g,d)}a&&b>0&&osa(g,b)}}else(f=a.oa)==null||f.classList.add("hidden")}},QN=function(a){for(const b of a.ra){let c;b.classList.toggle("hidden",!((c=a.h)==null||!c.value))}},RN=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];
for(const c of a){a=c.parentElement;let d;b=(d=a)==null?void 0:d.textContent;a&&b&&_ds.pf(a,_ds.Wf(b))}}},nsa=function(a,b){if(a=a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.pf(a,_ds.Wf(d))}},osa=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.M(hsa,{XI:b}),a.appendChild(b)},msa=async function(a,b){if(a.connected){var c=await _ds.v(),d=new _ds.xH,e=f=>{f=f.target;_ds.wH(d,f);a.ma.delete(f);
c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},ON=function(a,b){let c=!1;if(a.j)for(const d of a.j.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.Ej(a,"hidden","",d);return c},XN=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-selected");a=_ds.fm(_ds.C().pathname);a=`[href="${_ds.Sl(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.AH(c,"selected","true")},YN=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},psa=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.Zl(),await ZN(a),await a.Aa,
await _ds.v(),await _ds.Zl(),await ZN(a))},ZN=async function(a){if(a.connected&&a.j){await _ds.v();var b=a.j.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await qsa(a,b))}},qsa=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.io(b,a,!0).y;await _ds.Zl();c&&_ds.Ej(a,"user-scrolled","")}},MN=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},
bubbles:!0}))},$N=class extends _ds.Hj{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.oa=this.h=this.qa=this.j=null;this.ra=[];this.eventHandler=new _ds.E;this.ya=()=>{};this.ma=new Set;_ds.Dj(this,this.ea`animatable`,this.ea`aria-expanded`,this.ea`aria-label`,this.ea`collapsed`,this.ea`data-title`,this.ea`fixed`,this.ea`has-book-nav`,this.ea`hidden`,this.ea`top-level-nav`,this.ea`user-scrolled`,this.ea`visually-hidden`);this.background=
document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.g=_ds.M(fsa);this.m=_ds.M(gsa);this.Aa=new Promise(a=>{this.ya=a});this.ua=new _ds.Mn(()=>{this.connected&&LN(this)},20);this.va=new _ds.Mn(()=>{VN(this)},20);this.xa=new _ds.Mn(()=>{jsa(this)},100)}async connectedCallback(){this.connected=!0;_ds.Fk(this.background,this);this.hasAttribute("hidden")&&(_ds.Ej(this,"hidden","",this.g),_ds.Ej(this,"hidden","",this.m));let a;(a=this.parentElement)==null||a.insertBefore(this.g,
this.nextSibling);_ds.Ej(this,"aria-label","Hide side navigation",this.g);_ds.Ej(this,"data-title","Hide side navigation",this.g);_ds.Ej(this,"aria-expanded","true",this.g);let b;(b=this.parentElement)==null||b.insertBefore(this.m,this.nextSibling);if(this.qa=this.querySelector(".devsite-book-nav-filter"))this.h=this.qa.querySelector("input[type=text]"),this.oa=this.qa.querySelector(".filter-clear-button"),UN(this),WN(this);LN(this);lsa(this);await this.init();SN(this)}disconnectedCallback(){this.connected=
!1;this.eventHandler.removeAll();TN(this);this.ma.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.Ej(this,"visually-hidden","",a);a=[this.background,this.g,this.m];for(const b of a)b&&_ds.Hk(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.m.removeAttribute("animatable");this.m.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?
"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Ej(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);const c=[this.background,this.g,this.m];for(const d of c)d&&(b?_ds.Ej(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.ya()}async init(a=!0){if(this.connected){this.m.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.j=this.querySelector(".devsite-mobile-nav-bottom");_ds.Ej(this,"top-level-nav","");this.j&&this.j.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.Ej(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.Ej(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(XN(this),YN(this),await psa(this)):(await _ds.Zl(),await ZN(this))}}async ad(a){a?
(a=a.querySelector("nav")||null,XN(this,a),YN(this,a),a&&(await TN(this),this.ma.clear(),SN(this,a,!1)),_ds.Gj(this,this.querySelector("nav"),a)):_ds.Ek(this);UN(this);if(this.h){this.h.value="";let b;(b=this.oa)==null||b.classList.add("hidden");WN(this)}await _ds.Zl();await this.init(!1)}};$N.prototype.updateContent=$N.prototype.ad;$N.prototype.attributeChangedCallback=$N.prototype.attributeChangedCallback;$N.prototype.disconnectedCallback=$N.prototype.disconnectedCallback;
$N.prototype.connectedCallback=$N.prototype.connectedCallback;try{customElements.define("devsite-book-nav",$N)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
