(function(_ds){var window=this;var RO=function(){return"devsite-concierge"},vta=function(a){a.eventHandler.listen(a,"devsite-concierge-close-panel",()=>{document.body.getAttribute("concierge")==="modal"&&(a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),a.Cg=!1);SO(a,!0)});a.eventHandler.listen(a,"devsite-concierge-open-panel",c=>{c=c.getBrowserEvent().detail.nA;a.g(c,!0)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{document.body.getAttribute("concierge")==="modal"&&(a.Cg=!1,_ds.yv(a,
"concierge","open",document.body))});a.eventHandler.listen(a,"devsite-concierge-fullscreen-panel",()=>{a.Cg=!0;_ds.yv(a,"concierge","modal",document.body);a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0}))});a.eventHandler.listen(a,"devsite-concierge-dock-panel",c=>{c=c.getBrowserEvent();a.Cg=!1;_ds.yv(a,"concierge","open",document.body);c&&c.detail&&c.detail.hideSitemask&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))});a.eventHandler.listen(a,"devsite-concierge-set-notification",
c=>{c=c.getBrowserEvent();uta(a,c)});a.eventHandler.listen(a,"devsite-concierge-clear-notification",c=>{switch(c.getBrowserEvent().detail.tagName){case "devsite-concierge-ai-panel":a.Bj=!1;a.Kl="";break;case "devsite-concierge-info-panel":a.vk=!1;a.Om="";break;case "devsite-concierge-recommendations-panel":a.Ok=!1;a.Fn="";break;case "devsite-concierge-api-explorer-panel":a.Cj=!1;a.Ol="";break;case "devsite-concierge-my-activity-panel":a.Jk=!1,a.vn=""}});a.eventHandler.listen(document.body,"devsite-before-page-change",
()=>{a.largeViewport||SO(a)});const b=window.matchMedia("(min-width: 1400px)");a.largeViewport=b.matches;a.eventHandler.listen(b,"change",c=>{c=c.getBrowserEvent().matches;a.largeViewport=c});a.eventHandler.listen(document.body,"devsite-page-changed",()=>{TO(a)});a.eventHandler.listen(document.body,"devsite-viewport-change",c=>{c=c.getBrowserEvent().detail.viewport==="viewport--desktop";if(a.Tj)a.Ru=c,_ds.qv(a);else if(!c){c=document.body.getAttribute("concierge")==="modal";const d=document.body.getAttribute("concierge")===
"open";c&&(a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),a.Cg=!1);d&&(a.panelOpen=!1);if(c||d)SO(a,!0),_ds.qv(a)}});if(a.Tj){let c;(c=window.document.getElementsByClassName("devsite-devguide-mobile-button").item(0))==null||c.addEventListener("click",()=>{a.g("devsite-concierge-info-panel",!1)})}},TO=function(a){const b=_ds.C(),c=document.body.getAttribute("type");let d=document.body.hasAttribute("display-toc");if(c==="lcat"||c==="codelab")d=!1;else if(a.tenantId===1){if(b.pathname.match("^/learn[/]?")||
b.pathname.match("^/community[/]?")||b.pathname.match("^/solutions[/]?"))d=!0;c==="profile"&&(d=!0)}d?_ds.yv(a,"concierge",a.Cg?"modal":a.panelOpen?"open":"closed",document.body):_ds.yv(a,"concierge","hide",document.body);return d},SO=async function(a,b=!1){b&&await (await _ds.v()).getStorage().set("devguide_state","","CLOSED");await UO(a,!1)},uta=async function(a,b){const c=b.detail.tagName;b=b.detail.message;if(a.Ne!==c)switch(c){case "devsite-concierge-ai-panel":a.Bj&&(a.Bj=!1,a.Kl="",_ds.qv(a),
await a.j);a.Bj=!0;b&&(a.Kl=b);break;case "devsite-concierge-info-panel":a.vk&&(a.vk=!1,a.Om="",_ds.qv(a),await a.j);a.vk=!0;b&&(a.Om=b);break;case "devsite-concierge-recommendations-panel":a.Ok&&(a.Ok=!1,a.Fn="",_ds.qv(a),await a.j);a.Ok=!0;b&&(a.Fn=b);break;case "devsite-concierge-api-explorer-panel":a.Cj&&(a.Cj=!1,a.Ol="",_ds.qv(a),await a.j);a.Cj=!0;b&&(a.Ol=b);break;case "devsite-concierge-my-activity-panel":a.Jk&&(a.Jk=!1,a.vn="",_ds.qv(a),await a.j),a.Jk=!0,b&&(a.vn=b)}},VO=function(a,b,c=
0){if(b!==document.body&&b.parentElement){var {x:d,y:e,height:f}=b.getBoundingClientRect();return e+f>c&&d>0&&d<window.innerWidth?b:VO(a,b.parentElement,c)}},wta=async function(a,b){await _ds.v();var c,d,e;const f=((c=document)==null?void 0:(d=c.documentElement)==null?void 0:(e=d.getAttribute("dir"))==null?void 0:e.toLowerCase())==="rtl";(c=document.querySelector("devsite-header"))&&await customElements.whenDefined("devsite-header");c=(c==null?void 0:c.ma())||0;if(a=VO(a,b,c)){var {x:g,y:h,width:k,
height:l}=a.getBoundingClientRect();b=f?g+k:g;c=Math.max(h,c);d=f?Math.max(0,g):Math.min(g+k,window.innerWidth);e=Math.min(l-Math.abs(h),window.innerHeight);var m=Math.round(Math.max(5,(d-b)*.01));m=f?-m:m;var n=Math.round(Math.max(5,(e-c)*.01));g=b;h=c;for(var p=document.elementFromPoint(g,h),q=!1;p===a||!a.contains(p)||!q;){p&&(q=p.getBoundingClientRect().top>=c);g+=m;f?g<d&&(g=b,h+=n):g>d&&(g=b,h+=n);if(h>e)return;p=document.elementFromPoint(g,h)}return p}},UO=async function(a,b,c=""){a.Ne=c;if(a.panelOpen!==
b)if(c=document.querySelector(".devsite-article-body")){var d=await wta(a,c);d?(await _ds.vg(),c=d.getBoundingClientRect().top||0,a.panelOpen=b,document.body.dispatchEvent(new CustomEvent("devsite-sticky-resize",{bubbles:!0})),await _ds.Zl(),a=d.getBoundingClientRect().top||0,a-c!==0&&window.scrollBy({left:window.scrollX,top:a-c}),_ds.wg()):a.panelOpen=b}else a.panelOpen=b},WO=function(a,b){a.Ne!==b?(a.Ha({category:"Developer Concierge",action:a.panelOpen?"Switch Tab":"Open Panel",label:b}),a.g(b,
!0)):a.Cg||SO(a,!0)},xta=function(a,b,c,d){return c?d?(0,_ds.R)`<div class="devsite-concierge-notification-dot"></div>
      <div
        class="devsite-concierge-notification"
        @click="${()=>{WO(a,b)}}"
        >${d}</div
      >`:(0,_ds.R)`<div class="devsite-concierge-notification-dot"></div>`:(0,_ds.R)``},XO=function(a,b,c=!1){if(!c)return(0,_ds.R)``;a.ea.push(b);switch(b){case "devsite-concierge-ai-panel":return(0,_ds.R)` <devsite-concierge-ai-panel
          ?active="${a.Ne===b}">
        </devsite-concierge-ai-panel>`;case "devsite-concierge-info-panel":return(0,_ds.R)` <devsite-concierge-info-panel
          ?active="${a.Ne===b}">
        </devsite-concierge-info-panel>`;case "devsite-concierge-recommendations-panel":return(0,_ds.R)` <devsite-concierge-recommendations-panel
          ?active="${a.Ne===b}">
        </devsite-concierge-recommendations-panel>`;case "devsite-concierge-api-explorer-panel":return(0,_ds.R)` <devsite-concierge-api-explorer-panel
          ?active="${a.Ne===b}">
        </devsite-concierge-api-explorer-panel>`;case "devsite-concierge-my-activity-panel":return(0,_ds.R)` <devsite-concierge-my-activity-panel
          ?active="${a.Ne===b}">
        </devsite-concierge-my-activity-panel>`;default:return(0,_ds.R)` <div ?active="${a.Ne===b}">
          ${b} element missing
        </div>`}},YO=function(a,b,c,d,e,f=!1,g=!1,h=""){return f?(0,_ds.R)`
      <button class="${(0,_ds.Gt)({"devsite-concierge-menu-item--selected":a.Ne===b,"devsite-concierge-menu-item":!0,[`${b}--menu-item`]:!0})}"
          @click="${()=>{WO(a,b)}}"
          data-title="${d}">
        <div class="devsite-concierge-menu-icon" aria-hidden="true">
          ${e}
        </div>
        <div class="devsite-concierge-menu-title">
          ${c}
        </div>
        ${xta(a,b,g,h)}
      </button>`:(0,_ds.R)``},yta=function(a){return(0,_ds.R)` <div
      aria-label="${"Side panel menu"}"
      aria-orientation="${a.Tj&&!a.Cg&&a.panelOpen&&a.Ru?"horizontal":"vertical"}"
      class="devsite-concierge-menu"
      role="toolbar"
      @keydown="${b=>{if(b.key==="ArrowUp"||b.key==="ArrowDown"||b.key==="ArrowLeft"||b.key==="ArrowRight"){b.preventDefault();let c=0;const d=document.activeElement,e=a.querySelectorAll(".devsite-concierge-menu-item");d&&(c=[...e].indexOf(d));c=b.key==="ArrowUp"||b.key==="ArrowLeft"?c===0?e.length-1:c-1:c===e.length-1?0:c+1;e[c].focus()}}}">
      ${YO(a,"devsite-concierge-info-panel","Info","Page info",_ds.koa,a.jr,a.vk,a.Om)}
      ${YO(a,"devsite-concierge-ai-panel","Chat","Ask about this page",_ds.Lna,a.er,a.Bj,a.Kl)}
      ${YO(a,"devsite-concierge-recommendations-panel","Related","Related Pages",_ds.qoa,a.vr,a.Ok,a.Fn)}
      ${YO(a,"devsite-concierge-api-explorer-panel","API","APIs Explorer",_ds.Wna,a.gr,a.Cj,a.Ol)}
      ${YO(a,"devsite-concierge-my-activity-panel","Recent","Recent Activity",(0,_ds.Yt)`<svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17 12C15.7 12 14.6 12.84 14.18 14H9C7.9 14 7 13.1 7 12C7 10.9 7.9 10 9 10H11C13.21 10 15 8.21 15 6C15 3.79 13.21 2 11 2H5.82C5.4 0.84 4.3 0 3 0C1.34 0 0 1.34 0 3C0 4.66 1.34 6 3 6C4.3 6 5.4 5.16 5.82 4H11C12.1 4 13 4.9 13 6C13 7.1 12.1 8 11 8H9C6.79 8 5 9.79 5 12C5 14.21 6.79 16 9 16H14.18C14.59 17.16 15.69 18 17 18C18.66 18 20 16.66 20 15C20 13.34 18.66 12 17 12ZM3 4C2.45 4 2 3.55 2 3C2 2.45 2.45 2 3 2C3.55 2 4 2.45 4 3C4 3.55 3.55 4 3 4Z" fill="#1967D2"/></svg>`,
a.lr,a.Jk,a.vn)}
    </div>`},ZO=class extends _ds.zv{ib(){return this}constructor(){super(["devsite-tooltip"]);this.Cg=this.vr=this.lr=this.jr=this.gr=this.er=!1;this.Ru=(document.body.classList.contains("viewport--mobile")?"viewport--mobile":document.body.classList.contains("viewport--tablet")?"viewport--tablet":document.body.classList.contains("viewport--desktop")?"viewport--desktop":"")==="viewport--desktop";this.Ok=this.Jk=this.vk=this.Cj=this.Bj=this.Tj=!1;this.Ne=this.Fn=this.vn=this.Om=this.Ol=this.Kl="";
this.panelOpen=this.largeViewport=!1;this.eventHandler=new _ds.E;this.ea=[];this.m="UNDEFINED";this.tenantId=0;_ds.xv(this,(0,_ds.Ef)`concierge`)}async connectedCallback(){var a=await _ds.v();this.tenantId=a.getTenantId()||0;this.Tj=await a.hasMendelFlagAccess("Concierge","enable_devguide_mobile_view");super.connectedCallback();vta(this);if(TO(this)&&(a=_ds.C(),a.searchParams.has("devguide")))switch(a.searchParams.get("devguide")){case "ai":await this.g("devsite-concierge-ai-panel",!1);break;case "recommendations":await this.g("devsite-concierge-recommendations-panel",
!1);break;case "api_explorer":await this.g("devsite-concierge-api-explorer-panel",!1);break;case "my_activity":await this.g("devsite-concierge-my-activity-panel",!1);break;default:await this.g("devsite-concierge-info-panel",!1)}}disconnectedCallback(){super.disconnectedCallback();this.eventHandler.removeAll();document.body.removeAttribute("concierge")}async ma(a,b){await this.g("devsite-concierge-ai-panel");const c=this.querySelector("devsite-concierge-ai-panel"),d=_ds.C();d.search="";c&&await _ds.YJ(c,
{code:a,language:b,url:d.href})}async g(a,b=!1){b&&await (await _ds.v()).getStorage().set("devguide_state","","OPEN");await UO(this,!0,a)}static get observedAttributes(){return["data-ai-panel","data-api-explorer-panel","data-info-panel","data-my-activity-panel","data-recommendations-panel"]}attributeChangedCallback(a){switch(a){case "data-ai-panel":this.er=this.hasAttribute("data-ai-panel");_ds.wv("devsite-concierge-ai-panel");break;case "data-info-panel":this.jr=this.hasAttribute("data-info-panel");
_ds.wv("devsite-concierge-info-panel");break;case "data-recommendations-panel":this.vr=this.hasAttribute("data-recommendations-panel");_ds.wv("devsite-concierge-recommendations-panel");break;case "data-api-explorer-panel":this.gr=this.hasAttribute("data-api-explorer-panel");_ds.wv("devsite-concierge-api-explorer-panel");break;case "data-my-activity-panel":this.lr=this.hasAttribute("data-my-activity-panel"),_ds.wv("devsite-concierge-my-activity-panel")}}async h(a){super.h(a);a.has("largeViewport")&&
this.Ne===""&&this.largeViewport&&(this.m=await (await _ds.v()).getStorage().get("devguide_state","")||"UNDEFINED",this.m!=="CLOSED"&&(await this.g(this.ea[0]),this.Ha({category:"Developer Concierge",action:"Opened by default"})))}updated(a){super.updated(a);a.has("panelOpen")&&TO(this)}qa(){return TO(this)}render(){return(0,_ds.R)` <div class="${(0,_ds.Gt)({"devsite-concierge-panel-open":this.panelOpen,"devsite-concierge-container ":!0,"mobile-view-not-enabled":!this.Tj})}">
      ${yta(this)} ${(0,_ds.R)`<div class="devsite-concierge-panel">
      ${XO(this,"devsite-concierge-info-panel",this.jr)}
      ${XO(this,"devsite-concierge-ai-panel",this.er)}
      ${XO(this,"devsite-concierge-recommendations-panel",this.vr)}
      ${XO(this,"devsite-concierge-api-explorer-panel",this.gr)}
      ${XO(this,"devsite-concierge-my-activity-panel",this.lr)}
    </div>`}
    </div>`}};ZO.prototype.attributeChangedCallback=ZO.prototype.attributeChangedCallback;ZO.getTagName=RO;_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"er",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"gr",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"jr",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"lr",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"vr",void 0);
_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Cg",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Ru",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Tj",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Bj",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Cj",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"vk",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Jk",void 0);
_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Ok",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Kl",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Ol",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Om",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"vn",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Fn",void 0);_ds.w([_ds.H(),_ds.x("design:type",Object)],ZO.prototype,"Ne",void 0);
_ds.w([_ds.G({type:Boolean}),_ds.x("design:type",Object)],ZO.prototype,"largeViewport",void 0);_ds.w([_ds.G({type:Boolean}),_ds.x("design:type",Object)],ZO.prototype,"panelOpen",void 0);try{customElements.define(RO(),ZO)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteConcierge",a)};})(_ds_www);
